.\"
.\"Copyright (c) 2016 Frederic Culot <culot@FreeBSD.org>
.\"All rights reserved.
.\"
.\"Redistribution and use in source and binary forms, with or without
.\"modification, are permitted provided that the following conditions
.\"are met:
.\"1. Redistributions of source code must retain the above copyright
.\"   notice, this list of conditions and the following disclaimer
.\"   in this position and unchanged.
.\"2. Redistributions in binary form must reproduce the above copyright
.\"   notice, this list of conditions and the following disclaimer in the
.\"   documentation and/or other materials provided with the distribution.
.\"
.\"THIS SOFTWARE IS PROVIDED BY THE AUTHOR(S) ``AS IS'' AND ANY EXPRESS OR
.\"IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\"OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\"IN NO EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY DIRECT, INDIRECT,
.\"INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\"NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\"DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\"THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\"(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\"THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd November 09, 2016
.Dt PORTAL 1
.Os
.Sh NAME
.Nm portal
.Nd Front-end to pkg(8)
.Sh SYNOPSIS
.Nm
.Op Fl a
.Sh DESCRIPTION
Front-end to pkg(8).
.Pp
.Nm
provides the following features: packages listing
and searching, installation and deinstallation of packages,
and filtering based on the package state.
.Sh OPTIONS
The following option is supported by
.Nm :
.Bl -tag -width automatic
.It Fl v
Display the current version of
.Nm .
.El
.Sh INTERFACE
The user interface is made of two panels: the upper one
displays a list of packages sorted by category, and the bottom
one displays the description of the currently highlighted
package. Between those two panels lies an indicator of the
currently selected mode.
.Pp
In the upper panel which displays the packages list, the
following data appear from left to right:
.Bl -tag -width automatic
.It Status
The following markers are displayed depending on the package
status:
.Bl -tag -width automatic
.It +
The package is installed locally
.It +[-]
The package is installed locally and marked to be deleted
.It +[^]
The package is installed locally and is upgradable, meaning
a newer version is available from remote repositories
.It +[+]
The package is installed locally and marked to be upgraded
.It -
The package is not installed locally
.It -[+]
The package is not installed locally and marked to be
installed
.El
.It Name
The package name
.It Local version
The current version of the package if it is installed
.It Remote version
The latest version of the package available from remote
repositories
.El
.Pp
The lower panel displays the currently selected package's
comment line as found in the port's Makefile, together with
its longer comment as found in the port's pkg-descr file.
.Pp
The mode indicator found at the center of the screen between
the two main panels highlights the current mode. Its name will
also shortly appear above the indicator when switching mode.
.Sh MODES
By pressing the TAB key, the user can switch between the
following three available modes:
.Bl -tag -width automatic
.It Browse
This is the default mode, which displays the list of all
packages without any filtering.
.It Search
In this mode, one can search the list of packages for a
given string.
.It Filter
Four available filters can be applied to the list of
packages when this mode is selected. The four filters
can be toggled on or off by pressing the first letter
of the filter name:
.Bl -tag -width automatic
.It (A)vailable
To show or hide the available packages (those present in
the remote repository but not yet installed).
.It (I)nstalled
To show or hide installed packages.
.It (P)ending
To show or hide packages that have a pending action on
them, meaning they are either marked as to be installed
or removed.
.It (U)pgradable
To show or hide packages that are installed locally but
for which a newer version can be found in the remote
repository.
.El
.Sh KEYBINDINGS
.Bl -tag -width automatic
.It TAB
Cycle between modes.
.It Ctrl-C
Quit
.Nm.
.It Ctrl-X
Apply pending actions
(proceed with the installation / deinstallation of packages).
.It Ctrl-SPC
Mark currently highlighted package for installation.
.It Ctrl-D
Mark currently highlighted package for deletion.
.It Ctrl-N
Move down within the listing panel.
.It Ctrl-P
Move up within the listing panel.
.It PageUp
Scroll up the description panel.
.It PageDown
Scroll down the description panel.
.El
.Sh SEE ALSO
.Xr pkg 8
.Sh AUTHORS AND CONTRIBUTORS
.An Frederic Culot Aq culot@FreeBSD.org
.Sh BUGS
See the issue tracker at
.Em https://github.com/culot/portal/issues
.Pp
Please direct questions and issues to
.An Frederic Culot Aq culot@FreeBSD.org
